config/routes.rb
Elvin::Application.routes.draw do
  resources :groupc_users

  resources :groupcs

  resources :groupb_users

  resources :groupbs

  resources :groupa_users

  resources :groupas

  resources :colors

  devise_for :users

  resources :ordered_products

  resources :orders do
    post 'save_products', :on => :member
  end

  resources :products
  
  root :to => "users#index"

  resources :users

end

app/models/groupa_user.rb
class GroupaUser < ActiveRecord::Base
  belongs_to :groupa
  belongs_to :user
  
  def grpa_user_name
      user.try(:name)
  end

  def grpa_user_name=(name)
      obj_user = User.find_or_initialize_by_name(name) if name.present?
      self.user = if obj_user.new_record?
        obj_user.email = name+"@test.com" if obj_user.email.blank?
        obj_user.save(:validate=>false)
        obj_user
      else
        obj_user
      end
  end
end

app/controllers/groupa_users_controller.rb
class GroupaUsersController < ApplicationController
  # GET /groupa_users
  # GET /groupa_users.json
  def index
    @groupa_users = GroupaUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @groupa_users }
    end
  end

  # GET /groupa_users/1
  # GET /groupa_users/1.json
  def show
    @groupa_user = GroupaUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @groupa_user }
    end
  end

  # GET /groupa_users/new
  # GET /groupa_users/new.json
  def new
    @groupa_user = GroupaUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @groupa_user }
    end
  end

  # GET /groupa_users/1/edit
  def edit
    @groupa_user = GroupaUser.find(params[:id])
  end

  # POST /groupa_users
  # POST /groupa_users.json
  def create
    @groupa_user = GroupaUser.new(params[:groupa_user])

    respond_to do |format|
      if @groupa_user.save
        format.html { redirect_to @groupa_user, :notice => 'Groupa user was successfully created.' }
        format.json { render :json => @groupa_user, :status => :created, :location => @groupa_user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @groupa_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groupa_users/1
  # PUT /groupa_users/1.json
  def update
    @groupa_user = GroupaUser.find(params[:id])

    respond_to do |format|
      if @groupa_user.update_attributes(params[:groupa_user])
        format.html { redirect_to @groupa_user, :notice => 'Groupa user was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @groupa_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groupa_users/1
  # DELETE /groupa_users/1.json
  def destroy
    @groupa_user = GroupaUser.find(params[:id])
    @groupa_user.destroy

    respond_to do |format|
      format.html { redirect_to groupa_users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/groupa_users_helper.rb
module GroupaUsersHelper
end

app/views/groupa_users/_form.html.erb
<%= form_for(@groupa_user) do |f| %>
  <% if @groupa_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@groupa_user.errors.count, "error") %> prohibited this groupa_user from being saved:</h2>

      <ul>
      <% @groupa_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :groupa %><br />
    <%= f.text_field :groupa %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groupa_users/edit.html.erb
<h1>Editing groupa_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @groupa_user %> |
<%= link_to 'Back', groupa_users_path %>

app/views/groupa_users/index.html.erb
<h1>Listing groupa_users</h1>

<table>
  <tr>
    <th>Groupa</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groupa_users.each do |groupa_user| %>
  <tr>
    <td><%= groupa_user.groupa %></td>
    <td><%= groupa_user.user %></td>
    <td><%= link_to 'Show', groupa_user %></td>
    <td><%= link_to 'Edit', edit_groupa_user_path(groupa_user) %></td>
    <td><%= link_to 'Destroy', groupa_user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Groupa user', new_groupa_user_path %>

app/views/groupa_users/new.html.erb
<h1>New groupa_user</h1>

<%= render 'form' %>

<%= link_to 'Back', groupa_users_path %>

app/views/groupa_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Groupa:</b>
  <%= @groupa_user.groupa %>
</p>

<p>
  <b>User:</b>
  <%= @groupa_user.user %>
</p>


<%= link_to 'Edit', edit_groupa_user_path(@groupa_user) %> |
<%= link_to 'Back', groupa_users_path %>