config/routes.rb
Elvin::Application.routes.draw do
  resources :groupc_users

  resources :groupcs

  resources :groupb_users

  resources :groupbs

  resources :groupa_users

  resources :groupas

  resources :colors

  devise_for :users

  resources :ordered_products

  resources :orders do
    post 'save_products', :on => :member
  end

  resources :products
  
  root :to => "users#index"

  resources :users

end

app/models/groupb_user.rb
class GroupbUser < ActiveRecord::Base
  belongs_to :groupb
  belongs_to :user
  
  def grpb_user_name
      user.try(:name)
  end

  def grpb_user_name=(name)
      obj_user = User.find_or_initialize_by_name(name) if name.present?
      self.user = if obj_user.new_record?
        obj_user.email = name+"@test.com" if obj_user.email.blank?
        obj_user.save(:validate=>false)
        obj_user
      else
        obj_user
      end
  end
end

app/controllers/groupb_users_controller.rb
class GroupbUsersController < ApplicationController
  # GET /groupb_users
  # GET /groupb_users.json
  def index
    @groupb_users = GroupbUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @groupb_users }
    end
  end

  # GET /groupb_users/1
  # GET /groupb_users/1.json
  def show
    @groupb_user = GroupbUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @groupb_user }
    end
  end

  # GET /groupb_users/new
  # GET /groupb_users/new.json
  def new
    @groupb_user = GroupbUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @groupb_user }
    end
  end

  # GET /groupb_users/1/edit
  def edit
    @groupb_user = GroupbUser.find(params[:id])
  end

  # POST /groupb_users
  # POST /groupb_users.json
  def create
    @groupb_user = GroupbUser.new(params[:groupb_user])

    respond_to do |format|
      if @groupb_user.save
        format.html { redirect_to @groupb_user, :notice => 'Groupb user was successfully created.' }
        format.json { render :json => @groupb_user, :status => :created, :location => @groupb_user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @groupb_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groupb_users/1
  # PUT /groupb_users/1.json
  def update
    @groupb_user = GroupbUser.find(params[:id])

    respond_to do |format|
      if @groupb_user.update_attributes(params[:groupb_user])
        format.html { redirect_to @groupb_user, :notice => 'Groupb user was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @groupb_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groupb_users/1
  # DELETE /groupb_users/1.json
  def destroy
    @groupb_user = GroupbUser.find(params[:id])
    @groupb_user.destroy

    respond_to do |format|
      format.html { redirect_to groupb_users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/groupb_users_helper.rb
module GroupbUsersHelper
end

app/views/groupb_users/_form.html.erb
<%= form_for(@groupb_user) do |f| %>
  <% if @groupb_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@groupb_user.errors.count, "error") %> prohibited this groupb_user from being saved:</h2>

      <ul>
      <% @groupb_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :groupb %><br />
    <%= f.text_field :groupb %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groupb_users/edit.html.erb
<h1>Editing groupb_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @groupb_user %> |
<%= link_to 'Back', groupb_users_path %>

app/views/groupb_users/index.html.erb
<h1>Listing groupb_users</h1>

<table>
  <tr>
    <th>Groupb</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groupb_users.each do |groupb_user| %>
  <tr>
    <td><%= groupb_user.groupb %></td>
    <td><%= groupb_user.user %></td>
    <td><%= link_to 'Show', groupb_user %></td>
    <td><%= link_to 'Edit', edit_groupb_user_path(groupb_user) %></td>
    <td><%= link_to 'Destroy', groupb_user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Groupb user', new_groupb_user_path %>

app/views/groupb_users/new.html.erb
<h1>New groupb_user</h1>

<%= render 'form' %>

<%= link_to 'Back', groupb_users_path %>

app/views/groupb_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Groupb:</b>
  <%= @groupb_user.groupb %>
</p>

<p>
  <b>User:</b>
  <%= @groupb_user.user %>
</p>


<%= link_to 'Edit', edit_groupb_user_path(@groupb_user) %> |
<%= link_to 'Back', groupb_users_path %>